sudo: false

language: cpp

matrix:
  include:
    - env: ARCH="x86_64"
      os: linux
    - env: ARCH="x86_64"
      os: osx

# Use miniconda to install binary versions of numpy etc. from continuum
# analytic's repository. Follows an approach described by Dan Blanchard:
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  - chmod +x miniconda.sh
  # When we are installing the 32 Bit conda on a 64 Bit system, the miniconda
  # installer will ask for a "yes" despite the -b flag, so we pipe in a yes
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  #- bash miniconda.sh -b -p -f $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # install pythonocc-core
  - conda config --add channels https://conda.anaconda.org/conda-forge
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  - conda config --add channels https://conda.anaconda.org/oce
  # download and install ccad master from guillaume-florent repository
  - wget https://github.com/guillaume-florent/ccad/archive/master.zip -O ccad-master.zip
  - unzip ccad-master
  
script:
  # Test for python2
  - conda create -n testbbl2 python=2
  - source activate testbbl2
  - conda install -c pythonocc pythonocc-core=0.17.2
  - conda install jinja2
  - cd ccad-master
  - python setup.py install
  - cd ..
  - python generate.py
  - ls
  # Test for python3
  - conda create -n testbbl3 python=3.5
  - source activate testbbl3
  - conda install -c pythonocc pythonocc-core=0.17.2
  - conda install jinja2
  - cd ccad-master
  - python setup.py install
  - cd ..
  - python generate.py
  - ls

branches:
  only:
    - master
    - /^tp/
    - /^review/
